---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  vars:
    category_name: "NSX-Security-Group"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ virtualmachine_hostname }}"
      template: "{{ vcenter_system_template }}"
      datastore: Shared_NFS_Volume
      folder: vm
      state: poweredon
      cluster: "{{ cluster_name }}"
      hardware:
          memory_mb: "{{ virtualmachine_mem }}"
          num_cpus: "{{ virtualmachine_cpu }}"



