---
- name: Rename virtual machine from old name to new name using UUID
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  hosts: localhost
  tasks:
    - set_fact:
        vm_name: "{{ virtualmachine_hostname }}"
        new_vm_name: "PGTSDAV089_DO_NOT_DELETE"
        datacenter: "{{ datacenter_name }}"
        cluster_name: "{{ cluster_name }}"

    - name: Get VM "{{ virtualmachine_hostname }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        datacenter: "{{ datacenter_name }}"
        folder: "/GTS/Templates/Development/Ansible"
        name: "{{ vm_name }}"
      register: vm_facts

    - name: Rename "{{ vm_name }}" to "{{ new_vm_name }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        cluster: "{{ cluster_name }}"
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ new_vm_name }}"
