---
- name: Rename virtual machine from old name to new name using UUID
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  hosts: localhost
  tasks:
    - name: Rename "{{ virtualmachine_hostname }}" to "{{ virtualmachine_hostname_DONOTDELETE }}"
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        cluster: "{{ cluster_name }}"
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ virtualmachine_hostname_DONOTDELETE }}"
